### ISSUE TITLE
NanoRes characterization and integration

### ISSUE THREAD

**Issue by kchat79** [QuazarTech/Qrius#2]
Here is what Nishant has written over a mail.

-----------------------------------

Hi Mani and Krish,

The issue is that although using R0 we can get some numbers out  regarding the overall performance and bottlenecks, I am not completely  clear what is it that I need to give and in what form so that 
application group can take it forward.

Therefore right now I am simply listing out the situation as it stands.  Hopefully after a few discussions a clear path will emerge.

The questions that we are trying to answer are as follows:

1) What is the effect of contact (thermo-electric) potentials in our  present inserts / cabling. Is it of the order that can be measured using R0. If yes where is the major source identifiable. Also whether the measurement of resistance is affected due to the presence of these extra potentials.

2) Exactly same thing as above regarding the noise instead of contact potential. Also, when we connect a current source, that will also add some noise.

3) The minimum resistance that we can measure using a 10mA current source and how do we define the minimum accuracy regarding resistance measurement.

What I have is as follows:

1) A working R0 box which can amplify ±10 mV signal to ±10 V (1000x)  which is then fed to a 24 bit ADC of an existing XSMU. The accuracy is uncertain, it has some offset, and the noise levels are those which we got earlier. The gain can theoretically range from 1x to 1000000x, but  1000x is the one that we will operate on. Also the gain value is hard-coded in the firmware and cannot be changed through computer.

2) The is no firmware/driver for nano volt meter. The present ones hacked from the XSMU firmware and drivers. The driver presently can only be used to measure a voltage or the ADC value. For the current source another XSMU, but without any modifications of any form, will be required. Some codes are needed to talk to two XSMUs.

3) The input of R0 is shorted. I need to open them, put a connector, and make some suitable cabling to connect with the insert. I can only use the existing components, which may not be best suited for this 
application.

4) The insert that we would probably use first is the old RT insert and not the one with sample stage. There is right now shortage is of sample stages, and process of making them has only just begun. It will take some time to complete it.

This exercise that we are trying to do can have many stumbling blocks and far from ideal, but it is still important at this stage. The next version will solve many of the problems that R0 has currently, but the things beyond the nano volt meter are still obscure.

Although I can see some useful information coming out from this exercise, I still need some clarity regarding the approach.

Thanks and regards,
Nishant.

--------------------------------------------------

**Comment by mchandra** [comment]
What you copy-pasted is NOT an issue.
